version: '3.8'

services:
  iac-realtime-ai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iac_realtime_ai
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONPATH=/app
      - LOG_LEVEL=info
    env_file:
      - .env
    volumes:
      # Mount logs directory for persistent logging
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - iac-network

networks:
  iac-network:
    driver: bridge
