version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies for OpenAI token mint Lambda..."
      - pip install -r requirements.txt -t lib
      
  build:
    commands:
      - echo "Creating deployment package for openai-token-mint..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py
      - echo "Deployment package created successfully"
      
  post_build:
    commands:
      - echo "Updating Lambda function: openai-token-mint..."
      - aws lambda update-function-code --function-name openai-token-mint --zip-file fileb://deployment_package.zip
      - echo "Lambda function updated successfully!"
      - echo "Deployment completed at $(date)"

artifacts:
  files:
    - deployment_package.zip
  name: openai-token-mint-$(date +%Y-%m-%d-%H-%M-%S)
